# README
# ------
# This is the template which contains the "admin notifying
# email user new entry" - message. Don't modify anything
# except between the area beginning at # START # and
# ending at # END #.
# ------
########


# ADMIN NOTIFYING EMAIL -
# USER NEW ENTRY - MESSAGE.
# -------------------------
### START #################

$ADMIN_NAME has commented out your guestbook entry.

### END ###################