# README
# ------
# This is the template which contains the "admin notifying
# email user new entry" - message. Don't modify anything
# except between the area beginning at # START # and
# ending at # END #.
# ------
########


# ADMIN NOTIFYING EMAIL -
# USER NEW ENTRY - MESSAGE.
# -------------------------
### START #################

Announcement - New guestbook entry
----------------------------------

Time: $GUESTBOOK_NEW_ENTRY_TIME

Name: $GUESTBOOK_NEW_ENTRY_NAME_SUBMIT
Email: $GUESTBOOK_NEW_ENTRY_EMAIL_SUBMIT
Website: $GUESTBOOK_NEW_ENTRY_WEBSITE_SUBMIT

Message:  $GUESTBOOK_NEW_ENTRY_MESSAGE_SUBMIT

IP: $GUESTBOOK_NEW_ENTRY_IP

### END ###################

